export const data = [
    {id: 1, dating: 'Picnic in the park', type: 'Outdoor'},
    {id: 2, dating: 'Visit to the artificial ice rink', type: 'Active'},
    {
        id: 3,
        dating: 'Romantic dinner in an Italian restaurant',
        type: 'Culinary',
    },
    {
        id: 4,
        dating: 'Evening at the cinema with a favorite movie',
        type: 'Entertainment',
    },
    {id: 5, dating: 'Biking adventure around the city', type: 'Active'},
    {id: 6, dating: 'Photo session in the park', type: 'Creative'},
    {id: 7, dating: 'Exploration of local museums', type: 'Cultural'},
    {id: 8, dating: 'Boat ride on the lake', type: 'Romantic'},
    {id: 9, dating: 'Arcade games night out', type: 'Entertainment'},
    {id: 10, dating: 'Concert of a favorite band', type: 'Music'},
    {id: 11, dating: 'Themed home party', type: 'Creative'},
    {id: 12, dating: 'Relaxing spa day together', type: 'Wellness'},
    {id: 13, dating: 'Day at the amusement park', type: 'Entertainment'},
    {id: 14, dating: 'Rollerblading adventure', type: 'Active'},
    {id: 15, dating: 'Cooking dinner together', type: 'Culinary'},
    {id: 16, dating: 'Escape room challenge', type: 'Adventure'},
    {id: 17, dating: 'Watching the sunset by the beach', type: 'Romantic'},
    {id: 18, dating: 'Participating in a wine tasting', type: 'Culinary'},
    {id: 19, dating: 'Visiting thermal springs', type: 'Wellness'},
    {id: 20, dating: 'Role-playing game at a cafe', type: 'Creative'},
    {id: 21, dating: 'Nature bike ride', type: 'Active'},
    {id: 22, dating: 'Visit to the art and crafts fair', type: 'Cultural'},
    {id: 23, dating: 'Street art and sculpture festival', type: 'Creative'},
    {id: 24, dating: 'Flying a kite', type: 'Outdoor'},
    {id: 25, dating: 'Evening with board games', type: 'Entertainment'},
    {id: 26, dating: 'Attending a classical music concert', type: 'Music'},
    {id: 27, dating: 'Couples yoga session', type: 'Wellness'},
    {id: 28, dating: 'Mountain skiing adventure', type: 'Active'},
    {
        id: 29,
        dating: 'Exploring a contemporary art exhibition',
        type: 'Cultural',
    },
    {id: 30, dating: 'Sunrise meetup on a mountain', type: 'Outdoor'},
    {id: 31, dating: 'Theater performance', type: 'Entertainment'},
    {id: 32, dating: 'Tour of historical city landmarks', type: 'Cultural'},
    {id: 33, dating: 'Woodland picnic', type: 'Outdoor'},
    {id: 34, dating: 'Pottery art masterclass', type: 'Creative'},
    {id: 35, dating: 'Rooftop evening with city views', type: 'Romantic'},
    {id: 36, dating: 'Gastronomic tour', type: 'Culinary'},
    {id: 37, dating: 'Hiking with scenic views', type: 'Outdoor'},
    {id: 38, dating: 'Helicopter ride', type: 'Adventure'},
    {id: 39, dating: 'Hot springs bathing', type: 'Wellness'},
    {id: 40, dating: 'Ice cream by the waterfront', type: 'Culinary'},
    {id: 41, dating: 'Water sports: wakeboarding or kayaking', type: 'Active'},
    {id: 42, dating: 'Karaoke night', type: 'Music'},
    {id: 43, dating: 'Joint biking expedition', type: 'Active'},
    {id: 44, dating: 'Hot air balloon ride', type: 'Adventure'},
    {id: 45, dating: 'Thematic quest experience', type: 'Adventure'},
    {id: 46, dating: 'Rooftop sunset picnic', type: 'Romantic'},
    {id: 47, dating: 'Studio photo session', type: 'Creative'},
    {id: 48, dating: 'Circus performance', type: 'Entertainment'},
    {id: 50, dating: 'Gallery visit for contemporary art', type: 'Cultural'},
    {id: 51, dating: 'Stargazing in the great outdoors', type: 'Outdoor'},
    {id: 52, dating: 'Hot air balloon journey', type: 'Adventure'},
    {id: 53, dating: 'Couples book marathon', type: 'Cultural'},
    {id: 54, dating: 'Visit to the vintage car fair', type: 'Entertainment'},
    {id: 55, dating: 'Steampunk-themed photo session', type: 'Creative'},
    {id: 56, dating: 'Tandem bike adventure', type: 'Active'},
    {id: 57, dating: 'Sunset beach rendezvous', type: 'Romantic'},
    {
        id: 58,
        dating: 'Joint cooking lesson in Chinese cuisine',
        type: 'Culinary',
    },
    {id: 59, dating: 'Trip to the space museum', type: 'Cultural'},
    {id: 60, dating: 'Romantic decoration of the bedroom', type: 'Romantic'},
    {id: 61, dating: 'Couples yoga session', type: 'Wellness'},
    {id: 62, dating: 'Secret meeting in a rented room', type: 'Adventure'},
    {id: 63, dating: 'Swimming with dolphins', type: 'Adventure'},
    {id: 64, dating: 'Bowling with a romantic dinner', type: 'Entertainment'},
    {id: 65, dating: 'Couples plant care session', type: 'Wellness'},
    {
        id: 66,
        dating: 'Visit to a DIY jewelry-making workshop',
        type: 'Creative',
    },
    {id: 67, dating: 'Fireworks festival', type: 'Entertainment'},
    {id: 68, dating: 'Rope park adventure', type: 'Adventure'},
    {id: 69, dating: 'Water park and water slides', type: 'Entertainment'},
    {id: 70, dating: 'Biking excursion to a vineyard', type: 'Active'},
    {id: 71, dating: 'Attending a lecture on sciences', type: 'Educational'},
    {
        id: 72,
        dating: 'Learning the art of calligraphy together',
        type: 'Creative',
    },
    {id: 73, dating: 'Joint candle-making session', type: 'Creative'},
    {id: 74, dating: 'Visit to a farm for fresh produce', type: 'Culinary'},
    {id: 75, dating: 'Water bike excursion', type: 'Active'},
    {id: 76, dating: 'Puppet theater show', type: 'Entertainment'},
    {id: 77, dating: 'Flashmob in the city center', type: 'Entertainment'},
    {id: 78, dating: 'Playing mini-golf', type: 'Entertainment'},
    {id: 79, dating: 'Participating in a marathon run', type: 'Active'},
    {
        id: 80,
        dating: 'Starry night observation at an observatory',
        type: 'Outdoor',
    },
    {id: 81, dating: 'Lessons in salsa or tango', type: 'Dance'},
    {id: 82, dating: 'Pottery art class visit', type: 'Creative'},
    {id: 83, dating: 'Cafe date with live music', type: 'Music'},
    {id: 84, dating: 'Making homemade dumplings together', type: 'Culinary'},
    {id: 85, dating: 'Boat picnic with aromatic candles', type: 'Romantic'},
    {id: 86, dating: 'Billiards game night', type: 'Entertainment'},
    {id: 87, dating: 'Extreme quad biking', type: 'Adventure'},
    {id: 88, dating: 'Hot air kite flying', type: 'Adventure'},
    {id: 89, dating: 'Visit to a festival of fruit tastings', type: 'Culinary'},
    {id: 90, dating: 'Romantic dinner on a yacht', type: 'Romantic'},
    {id: 91, dating: 'Joint animal shelter volunteer day', type: 'Charity'},
    {id: 92, dating: 'Attending a dance battle', type: 'Dance'},
    {id: 93, dating: 'Costume-making workshop for Halloween', type: 'Creative'},
    {
        id: 94,
        dating: 'Sunset meet-up on a rooftop with blankets',
        type: 'Romantic',
    },
    {id: 95, dating: 'Joint snowboarding adventure', type: 'Active'},
    {id: 96, dating: 'Picnic in the botanical garden', type: 'Outdoor'},
    {id: 97, dating: 'Open-air themed movie event', type: 'Entertainment'},
    {
        id: 98,
        dating: 'Visit to unique city geographical points',
        type: 'Adventure',
    },
    {id: 99, dating: 'Joint nature painting session', type: 'Creative'},
    {id: 100, dating: 'Visit to an extreme sports arena', type: 'Adventure'},
];
